### ISSUE TITLE
Improve edit branch

### ISSUE THREAD

**Issue by drichtarik** [marmiskeje/PA165CarPark2017#71]
For example when editing a branch: Show which cars are already in it

**Comment by mkralik3** [comment]
* Window looks like for create
* Values which are already in branch should be predefined (cars, managers)

**Comment by mkralik3** [comment]
From reviews:
- Při editaci nelze přidat auto zaškrtáváním, je nutné použít Assign Car
- Při editaci se nepředvyplní Manager

**Comment by tomaspvk** [comment]
Done in 851e738757ecdc7dd73a9b335a4b2d5b96933343
